"""EMG-prior w-sensitivity learning curves, dark-theme transparent PNGs for slides.
One PNG per body (h0918/h1622/h2190). Self-contained: loads log.csv directly.

Redone 2026-09-11, twice. First redo: w-sensitivity ladder specifically
(only prior / +0.1 / +0.5 residual / no prior), NOT the content-necessity
ladder (real vs. untrained vs. null) -- that comparison (real content doesn't
beat a random decoder on raw episode score) is a separate, already-reported
finding, not something this chart hides -- see the *_prior_variants.png
generated by an earlier version of this script, and
project_prior_characterization_2026 / project_paper_spine_2026 for why the
paper's load-bearing claim was already reframed off raw RL score onto
per-muscle activation fidelity (BF/ST/GMED), where the dissociation this
score-based ladder shows is expected, not a problem to hide.

Second redo: dropped the sample-efficiency and stability bar panels from the
first version -- checked DEP-RL (Schumacher 2023), LAP (Hausdorfer 2024),
the same-body MPO paper (arXiv:2309.02976), and Park et al. 2026 directly
(fetched each paper's own text, not assumed), and none of them plot anything
like that. All four show exactly one thing: mean +/- SD across seeds vs.
training steps, Park et al. with a moving-average smoothing pass. The SD
band and the visible wobble in the line itself already carry the stability
story -- that's how the literature shows it too, no separate panel needed.
This version matches that convention directly instead of inventing our own.

test/episode_score/mean is the mean over 20 held-out test rollouts
(test/episode_score/size == 20 in every log.csv checked) run with the
current checkpoint at that training step -- not a single episode, and not
the noisier on-policy training-episode return (that's train/episode_score/*,
a different column, not plotted here).

Third redo (2026-09-11): legend/summary numbers now pull the OFFICIAL
checkpoint_rule.md numbers (t*-selected checkpoint, fresh N=100 re-eval,
real fall%) from results/checkpoint_selection/<label>_reeval.csv when one
exists, instead of "mean of the raw curve's last logged point." The two
disagree materially wherever a condition peaks then declines before 20M --
h2190 w=0.5 was 273 by the old method, 440 by the real one; untrained
decoder was 177, really 606. The plotted LINE is unchanged (still the full
training-curve mean+-SD, smoothed) -- only the summary number in the
legend/console changed, because that's the only piece that was ever a
shortcut standing in for the real re-eval.

Smoothing: Park et al. use a 10-point moving average, but that's on a 75M-
step budget (~10 evals = ~2.7% of budget). Our epoch_steps=2e5 over a
budget an order of magnitude smaller means a literal 10-point window would
smear the entire rise phase (which happens inside ~5-15 epochs on these
bodies) into mush. SMOOTH_WINDOW=3 (0.6M steps) keeps the same intent --
denoise without erasing real differentiation -- scaled to this project's
own epoch spacing rather than copying an absolute number that assumed a
much longer run.
"""
import csv
import glob
import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

LIVE = "/media/calc_2/scone_results/live/lalitha/final_experiments"
FIG_DIR = "/home/nadinebadie/lalitha/LEAPS/notes/figures"
CHECKPOINT_DIR = "/home/nadinebadie/lalitha/LEAPS/results/checkpoint_selection"

# Legend numbers now come from the official locked rule (t* selected per
# seed, fresh N=100 re-eval at that checkpoint -- see checkpoint_rule.md),
# not "mean of the last logged point," which understates any condition that
# peaks then declines (confirmed materially wrong for h2190 w=0.5/untrained:
# final-at-20M said 273/177, the real t*-reeval number is 440/606).
_OFFICIAL_LABEL = {
    "MPO (backbone)": "mpo_{body}_onlyvelrew",
    "DEP-MPO (backbone)": "depmpo_{body}_onlyvelrew",
    "EMG prior (ours, w=0.1)": "emg_lap_{body}_w01_onlyvelrew",
    "prior + 0.1 residual": "emg_lap_{body}_w01_onlyvelrew",
    "only prior (w=0.0)": "emg_lap_{body}_w00_onlyvelrew",
    "prior + 0.5 residual": "emg_lap_{body}_w05_onlyvelrew",
    "no prior (null)": "null_{body}_onlyvelrew",
    "untrained decoder": "untrainedlap_{body}_w05_onlyvelrew",
}


def load_official(body: str, condition: str):
    tmpl = _OFFICIAL_LABEL.get(condition)
    if tmpl is None:
        return None
    path = f"{CHECKPOINT_DIR}/{tmpl.format(body=body)}_reeval.csv"
    if not os.path.exists(path):
        return None
    rows = list(csv.DictReader(open(path)))
    if not rows:
        return None
    means = [float(r["reeval_mean"]) for r in rows]
    falls = [float(r["fall_pct"]) for r in rows]
    return dict(mean=float(np.mean(means)), sd=float(np.std(means)),
                fall=float(np.mean(falls)), n=len(rows))

# dark-mode categorical steps (palette.md slots 1-4) -- fixed per condition
# name so the same condition keeps the same color across every body's figure.
COLOR_BY_LABEL = {
    "only prior (w=0.0)": "#3987e5",
    "prior + 0.1 residual": "#d95926",
    "prior + 0.5 residual": "#199e70",
    "no prior (null)": "#c98500",
    "untrained decoder": "#d55181",
    "MPO (backbone)": "#a0a0a0",
    "DEP-MPO (backbone)": "#9085e9",
    "EMG prior (ours, w=0.1)": "#d95926",  # same orange as "prior + 0.1 residual" -- same condition
}

# MPO/DEP-MPO backbones (no wrapper at all) vs. "ours" (the w=0.1 EMG-prior
# condition -- matches RETURN_TABLE.csv's own "EMG prior" bucket, confirmed
# by seed count: h2190 n=4 there matches emg_lap w01 seed0-3). h2190 MPO/
# DEP-MPO seed2 excluded from both -- only ran to 5M (a short/incomplete
# run), same exclusion RETURN_TABLE.csv itself made (n=2, not 3, for both
# backbones on h2190). DEP-MPO h2190 seed1 lives at a differently-named
# config (`h2190_noclip_net256_onlyvelrew_seed1`), confirmed via
# results/checkpoint_selection/depmpo_h2190_onlyvelrew.csv, not a naming
# mistake here.
BACKBONE_COMPARISON = {
    "h0918": {
        "MPO (backbone)": [f"{LIVE}/mpo/h0918/h0918_onlyvelrew_seed{s}" for s in (0, 1, 2)],
        "DEP-MPO (backbone)": [f"{LIVE}/dep-mpo/h0918/h0918_onlyvelrew_dep_seed{s}" for s in (0, 1, 2)],
        "EMG prior (ours, w=0.1)": [
            f"{LIVE}/emg_lap/h0918/h0918_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
    },
    "h1622": {
        "MPO (backbone)": [f"{LIVE}/mpo/h1622/h1622_onlyvelrew_seed{s}" for s in (0, 1, 2)],
        "DEP-MPO (backbone)": [f"{LIVE}/dep-mpo/h1622/h1622_onlyvelrew_dep_seed{s}" for s in (0, 1, 2)],
        "EMG prior (ours, w=0.1)": [
            f"{LIVE}/emg_lap/h1622/h1622_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
    },
    "h2190": {
        "MPO (backbone)": [f"{LIVE}/mpo/h2190/h2190_onlyvelrew_seed{s}" for s in (0, 1)],
        "DEP-MPO (backbone)": [
            f"{LIVE}/dep-mpo/h2190/h2190_onlyvelrew_dep_seed0",
            f"{LIVE}/dep-mpo/h2190/h2190_noclip_net256_onlyvelrew_seed1",
        ],
        "EMG prior (ours, w=0.1)": [
            f"{LIVE}/emg_lap/h2190/h2190_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
    },
}

# All 5 synergy-prior variations for h0918 (only this body has an untrained-
# decoder arm at every w) -- separate from BODIES' 4-condition w-sensitivity
# ladder below. Same plotting path, different condition set + output name.
H0918_ALL_VARIANTS = {
    "only prior (w=0.0)": [
        f"{LIVE}/emg_lap/h0918/h0918_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "prior + 0.1 residual": [
        f"{LIVE}/emg_lap/h0918/h0918_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2)
    ],
    "prior + 0.5 residual": [
        f"{LIVE}/emg_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "no prior (null)": [
        f"{LIVE}/no_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1, 2)
    ],
    "untrained decoder": [
        f"{LIVE}/untrained_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_untrainedprior_seed{s}" for s in (0, 1)
    ],
}

H1622_ALL_VARIANTS = {
    "only prior (w=0.0)": [
        f"{LIVE}/emg_lap/h1622/h1622_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "prior + 0.1 residual": [
        f"{LIVE}/emg_lap/h1622/h1622_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
    ],
    "prior + 0.5 residual": [
        f"{LIVE}/emg_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "no prior (null)": [
        f"{LIVE}/no_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1, 2)
    ],
    "untrained decoder": [
        f"{LIVE}/untrained_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_untrainedprior_seed{s}" for s in (0, 1)
    ],
}

H2190_ALL_VARIANTS = {
    "only prior (w=0.0)": [
        f"{LIVE}/emg_lap/h2190/h2190_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "prior + 0.1 residual": [
        f"{LIVE}/emg_lap/h2190/h2190_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
    ],
    "prior + 0.5 residual": [
        f"{LIVE}/emg_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
    ],
    "no prior (null)": [
        f"{LIVE}/no_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1)
    ],
    "untrained decoder": [
        f"{LIVE}/untrained_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_untrainedprior_seed{s}" for s in (0, 1)
    ],
}

BODIES = {
    "h0918": {
        "only prior (w=0.0)": [
            f"{LIVE}/emg_lap/h0918/h0918_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "prior + 0.1 residual": [
            f"{LIVE}/emg_lap/h0918/h0918_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "no prior (null)": [
            f"{LIVE}/no_lap/h0918/h0918_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1, 2)
        ],
    },
    "h1622": {
        "only prior (w=0.0)": [
            f"{LIVE}/emg_lap/h1622/h1622_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "prior + 0.1 residual": [
            f"{LIVE}/emg_lap/h1622/h1622_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "no prior (null)": [
            f"{LIVE}/no_lap/h1622/h1622_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1, 2)
        ],
    },
    "h2190": {
        "only prior (w=0.0)": [
            f"{LIVE}/emg_lap/h2190/h2190_k6_w00_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "prior + 0.1 residual": [
            f"{LIVE}/emg_lap/h2190/h2190_k6_w01_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1, 2, 3)
        ],
        "prior + 0.5 residual": [
            f"{LIVE}/emg_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_seed{s}" for s in (0, 1)
        ],
        "no prior (null)": [
            f"{LIVE}/no_lap/h2190/h2190_k6_w05_onlyvelrew_AB06_corrected_null_seed{s}" for s in (0, 1)
        ],
    },
}

MAX_STEPS = 20e6      # h2190 w01 seed0 ran to 71M (a separate extension, see
                       # queue.txt 2026-08-31) -- truncate every seed to the
                       # 20M budget every other seed in this comparison used.
SMOOTH_WINDOW = 3      # epochs (0.6M steps) -- see module docstring

INK_PRIMARY = "#ffffff"
INK_SECONDARY = "#c3c2b7"
INK_MUTED = "#898781"
GRID = (1, 1, 1, 0.08)
BASELINE = (1, 1, 1, 0.25)

plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = ["DejaVu Sans"]


def moving_average(x: np.ndarray, window: int) -> np.ndarray:
    """Centered moving average, edges shrink the window rather than pad --
    matches np.convolve('same') without smearing zeros in at the boundaries."""
    out = np.empty_like(x)
    half = window // 2
    for i in range(len(x)):
        lo, hi = max(0, i - half), min(len(x), i + half + 1)
        out[i] = x[lo:hi].mean()
    return out


def load_condition(dirs: list[str]) -> dict:
    steps_ref = None
    test_curves = []
    for d in dirs:
        p = glob.glob(f"{d}/*/log.csv")[0]
        df = pd.read_csv(p)
        df = df[df["train/steps"] <= MAX_STEPS]
        steps = df["train/steps"].to_numpy()
        if steps_ref is None:
            steps_ref = steps
        assert len(steps) == len(steps_ref), f"{d} length mismatch"
        test_curves.append(df["test/episode_score/mean"].to_numpy())
    test_arr = np.stack(test_curves)
    mean_raw = test_arr.mean(axis=0)
    std_raw = test_arr.std(axis=0)
    return dict(
        steps=steps_ref,
        test_mean=moving_average(mean_raw, SMOOTH_WINDOW),
        test_std=moving_average(std_raw, SMOOTH_WINDOW),
        n_seeds=len(dirs),
        final_test_mean=test_arr[:, -1].mean(), final_test_std=test_arr[:, -1].std(),
    )


def plot_body(body: str, conditions: dict[str, list[str]], show_legend: bool = True,
              out_name: str = None, title_suffix: str = "w-sensitivity",
              legend_loc: str = "best", legend_below: bool = False) -> None:
    order = list(conditions.keys())
    results = {label: load_condition(dirs) for label, dirs in conditions.items()}

    # x-axis trim: convergence (first point within 10% of this body's best
    # smoothed score) + 1M steps -- the flat tail carries no information
    # once every condition has plateaued. Purely a display choice, disclosed
    # on the chart; all seeds/steps still went into the computed stats above.
    #
    # BUT only trim when most conditions actually reach that bar. On h2190,
    # only one of five conditions (no-prior) ever gets within 10% of the
    # peak within the trimmed window -- the other four are still climbing
    # toward their OWN later, unrelated peaks (verified directly: untrained
    # decoder peaks at 651 around 8.2M, only-prior at 383 around 11.6M --
    # both well past where an early trim would have cut them off, making
    # them look flat/dead when they're not). Trimming here would hide a
    # real breakthrough-then-decline pattern in 4 of 5 conditions, not just
    # cut an uninformative tail. Require a majority of conditions to have
    # converged before trimming; otherwise show the full run.
    peak_ref = max(r["test_mean"].max() for r in results.values())
    target = 0.9 * peak_ref
    conv_points = []
    for r in results.values():
        reached = r["test_mean"] >= target
        if reached.any():
            conv_points.append(r["steps"][int(np.argmax(reached))] / 1e6)
    full_range_m = max(r["steps"].max() for r in results.values()) / 1e6
    if conv_points and len(conv_points) >= len(order) / 2:
        x_trim = min(full_range_m, max(conv_points) + 1.0)
    else:
        x_trim = full_range_m

    fig = plt.figure(figsize=(9.5, 6.1 if legend_below else 5.6), dpi=200)
    fig.patch.set_alpha(0)
    ax_bottom = 0.24 if legend_below else 0.13
    ax_height = 0.65 if legend_below else 0.72
    ax = fig.add_axes([0.09, ax_bottom, 0.88, ax_height])
    ax.set_facecolor("none")

    for label in order:
        r = results[label]
        x = r["steps"] / 1e6
        c = COLOR_BY_LABEL[label]
        official = load_official(body, label)
        if official:
            legend_label = (f"{label}  ({official['mean']:.0f}±{official['sd']:.1f} @ t*, "
                             f"fall {official['fall']:.0f}%, n={official['n']})")
        else:
            legend_label = f"{label}  ({r['final_test_mean']:.0f}±{r['final_test_std']:.1f} @ 20M, n={r['n_seeds']})"
        ax.plot(x, r["test_mean"], color=c, linewidth=2.0, label=legend_label, zorder=3)
        ax.fill_between(x, r["test_mean"] - r["test_std"], r["test_mean"] + r["test_std"],
                         color=c, alpha=0.15, linewidth=0, zorder=2)

    ax.set_xlim(0, x_trim)
    ax.set_ylim(0, 1050)
    ax.set_xlabel("training steps (millions)", color=INK_SECONDARY, fontsize=10)
    ax.set_ylabel("test episode score (mean of 20 rollouts)", color=INK_SECONDARY, fontsize=10)
    ax.tick_params(colors=INK_MUTED, labelsize=9)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.spines["bottom"].set_visible(True)
    ax.spines["bottom"].set_color(BASELINE)
    ax.grid(axis="y", color=GRID, linewidth=1, zorder=0)
    ax.set_axisbelow(True)
    if show_legend:
        if legend_below:
            ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.22), ncol=2,
                      frameon=False, fontsize=9, labelcolor=INK_PRIMARY, handlelength=1.6)
        else:
            ax.legend(loc=legend_loc, frameon=False, fontsize=9, labelcolor=INK_PRIMARY, handlelength=1.6)
    ax.set_title(
        f"{body.upper()} — EMG-prior {title_suffix} (mean ± 1 SD, {SMOOTH_WINDOW}-epoch moving avg.)",
        color=INK_PRIMARY, fontsize=12.5, loc="left", pad=12, fontweight="bold",
    )
    if x_trim < full_range_m:
        ax.text(
            1.0, 1.0, f"x-axis cut at convergence+1M (full run: {full_range_m:.0f}M)",
            transform=ax.transAxes, ha="right", va="bottom", color=INK_MUTED, fontsize=8,
        )

    out = f"{FIG_DIR}/{out_name or f'{body}_prior_wsensitivity'}.png"
    fig.savefig(out, transparent=True, dpi=200)
    plt.close(fig)
    print(f"saved {out}")
    for label in order:
        r = results[label]
        official = load_official(body, label)
        if official:
            print(f"  {label:24s} n={official['n']}  official={official['mean']:.1f}±{official['sd']:.1f} @ t*"
                  f"  fall={official['fall']:.0f}%")
        else:
            print(f"  {label:24s} n={r['n_seeds']}  final(20M)={r['final_test_mean']:.1f}±{r['final_test_std']:.1f}"
                  f"  [no official t*-reeval for this condition]")


SHOW_LEGEND = False  # user hand-labels every chart in PPT -- colors stay fixed
                     # (COLOR_BY_LABEL), only the in-figure legend box is dropped.
                     # Per-condition numbers still print to console below.

if __name__ == "__main__":
    for body, conditions in BODIES.items():
        plot_body(body, conditions, show_legend=SHOW_LEGEND)
    # All 5 synergy-prior variations, one slide per body -- separate from the
    # 4-condition w-sensitivity ladder above.
    plot_body("h0918", H0918_ALL_VARIANTS, out_name="h0918_prior_variants", title_suffix="variants",
              show_legend=SHOW_LEGEND)
    plot_body("h1622", H1622_ALL_VARIANTS, out_name="h1622_prior_variants", title_suffix="variants",
              show_legend=SHOW_LEGEND)
    plot_body("h2190", H2190_ALL_VARIANTS, out_name="h2190_prior_variants", title_suffix="variants",
              show_legend=SHOW_LEGEND)
    # MPO / DEP-MPO (true, unwrapped backbones) vs. ours (w=0.1 EMG prior).
    for body in ("h0918", "h1622", "h2190"):
        plot_body(body, BACKBONE_COMPARISON[body], out_name=f"{body}_vs_backbones",
                  title_suffix="vs. unwrapped backbones", show_legend=SHOW_LEGEND)
